import matplotlib as mpl
from cycler import cycler


#########################################################
# Figure layout defaults
#########################################################
fcp_params = {'ax_edge_color': '#aaaaaa',
              'ax_fill_color': '#eaeaea',
              'ax_size': [400,400],  # [width, height]
              'box_divider_color': '#bbbbbb',
              'box_fill_color': '#ffffff',
              'box_group_title_edge_color': '#ffffff',
              'box_group_title_fill_color': '#ffffff',
              'box_group_title_font_size': 13,
              'box_group_title_font_color': '#666666',
              'box_group_title_font_style': 'normal',
              'box_group_title_font_weight': 'normal',
              'box_group_label_edge_color': '#aaaaaa',
              'box_group_label_font_size': 12,
              'box_group_label_font_color': '#666666',
              'box_group_label_font_style': 'normal',
              'box_group_label_font_weight': 'normal',
              'cbar_size': 30,
              'cmap': 'inferno',
              'dpi': 100,
              'fig_edge_color': '#ffffff',
              'fig_fill_color': '#ffffff',
              'grid_major_color': '#ffffff',
              'grid_major_style': '-',
              'grid_major_width': 1.3,
              'grid_minor_color': '#ffffff',
              'grid_minor_style': 'dotted',
              'grid_minor_width': 0.5,
              'label_color': 'k',
              'label_font_size': 14,
              'label_style': 'italic',
              'label_weight': 'bold',
              'legend_fill_color': '#ffffff',
              'legend_edge_color': '#ffffff',
              'legend_font_size': 12,
              'legend_points': 1,
              'legend_title': '',
              'lines_width': 1,
              'marker_size': 7,
              'marker_type': 'o',
              'rc_label_edge_color': '#8c8c8c',
              'rc_label_fill_color': '#8c8c8c',
              'rc_label_font_size': 16,
              'rc_label_text_color': '#ffffff',
              'rc_label_text_style': 'normal',
              'rc_label_text_weight': 'bold',
              'rc_label_size': 30,
              'tick_labels_font_size': 12,
              'tick_labels_color': '#000000',
              'ticks_major_color': '#ffffff',
              'ticks_minor_color': '#ffffff',
              'ticks_major_length': 6,
              'ticks_major_width': 1.7,
              'title_fill_color': '#ffffff',
              'title_edge_color': '#ffffff',
              'title_font_color': '#333333',
              'title_font_size': 18,
              'title_font_weight': 'bold',
              'wrap_title_edge_color': '#5f5f5f',
              'wrap_title_fill_color': '#5f5f5f',
              'wrap_title_font_size': 16,
              'wrap_title_font_color': '#ffffff',
              'wrap_title_font_style': 'normal',
              'wrap_title_font_weight': 'bold',
              'wrap_title_size': 30,
              }

#########################################################
# New color schemes
#########################################################

# colors = []

####################################################
# Default marker scheme
####################################################

# markers = []

# ####################################################
# # Matplotlib default overrides
# ####################################################

# rcParams = {'agg.path.chunksize': 0,
#             'animation.avconv_args': [''],
#             'animation.avconv_path': 'avconv',
#             'animation.bitrate': -1,
#             'animation.codec': 'mpeg4',
#             'animation.convert_args': [''],
#             'animation.convert_path': 'convert',
#             'animation.ffmpeg_args': [''],
#             'animation.ffmpeg_path': 'ffmpeg',
#             'animation.frame_format': 'png',
#             'animation.mencoder_args': [''],
#             'animation.mencoder_path': 'mencoder',
#             'animation.writer': 'ffmpeg',
#             'axes.axisbelow': True,
#             'axes.prop_cycle': cycler('color', palette),
#             'axes.edgecolor': '#ffffff',
#             'axes.facecolor': '#eaeaea',
#             'axes.formatter.limits': [-4, 4],
#             'axes.formatter.use_locale': False,
#             'axes.formatter.use_mathtext': True,
#             'axes.formatter.useoffset': True,
#             'axes.grid': True,
#             'axes.grid.which': 'major',
#             'axes.labelcolor': 'k',
#             'axes.labelsize': 14.0,
#             'axes.labelweight': 'bold',
#             'axes.linewidth': 1.0,
#             'axes.titlesize': 16.0,
#             'axes.titleweight': 'normal',
#             'axes.unicode_minus': True,
#             'axes.xmargin': 0.0,
#             'axes.ymargin': 0.0,
#             'axes3d.grid': True,
#             'backend': 'Qt4Agg',
#             'backend.qt4': 'PyQt4',
#             'backend.qt5': 'PyQt5',
#             'backend_fallback': True,
#             'contour.negative_linestyle': 'dashed',
#             'docstring.hardcopy': False,
#             'examples.directory': '',
#             'figure.autolayout': False,
#             'figure.dpi': 80.0,
#             'figure.edgecolor': 'w',
#             'figure.facecolor': '1.0',
#             'figure.figsize': [7.0,7.0],
#             'figure.frameon': True,
#             'figure.max_open_warning': 20,
#             'figure.subplot.bottom': 0.1,
#             'figure.subplot.hspace': 0.2,
#             'figure.subplot.left': 0.125,
#             'figure.subplot.right': 0.9,
#             'figure.subplot.top': 0.9,
#             'figure.subplot.wspace': 0.2,
#             'font.cursive': ['Apple Chancery',
#                              'Textile',
#                              'Zapf Chancery',
#                              'Sand',
#                              'cursive'],
#             'font.family': ['sans-serif'],
#             'font.fantasy': ['Comic Sans MS',
#                              'Chicago',
#                              'Charcoal',
#                              'ImpactWestern',
#                              'fantasy'],
#             'font.monospace': ['Bitstream Vera Sans Mono',
#                                'DejaVu Sans Mono',
#                                'Andale Mono',
#                                'Nimbus Mono L',
#                                'Courier New',
#                                'Courier',
#                                'Fixed',
#                                'Terminal',
#                                'monospace'],
#             'font.sans-serif': ['Arial',
#                                 'Bitstream Vera Sans',
#                                 'Lucida Grande',
#                                 'Verdana',
#                                 'Geneva',
#                                 'Lucid',
#                                 'Helvetica',
#                                 'Avant Garde',
#                                 'sans-serif'],
#             'font.serif': ['Bitstream Vera Serif',
#                            'DejaVu Serif',
#                            'New Century Schoolbook',
#                            'Century Schoolbook L',
#                            'Utopia',
#                            'ITC Bookman',
#                            'Bookman',
#                            'Nimbus Roman No9 L',
#                            'Times New Roman',
#                            'Times',
#                            'Palatino',
#                            'Charter',
#                            'serif'],
#             'font.size': 12.5,
#             'font.stretch': 'normal',
#             'font.style': 'normal',
#             'font.variant': 'normal',
#             'font.weight': 'normal',
#             'grid.alpha': 1.0,
#             'grid.color': '#ffffff',
#             'grid.linestyle': '-',
#             'grid.linewidth': 1.5,
#             'image.aspect': 'equal',
#             'image.cmap': 'inferno',
#             'image.interpolation': 'bilinear',
#             'image.lut': 256,
#             'image.origin': 'upper',
#             'image.resample': False,
#             'interactive': True,
#             'keymap.all_axes': ['a'],
#             'keymap.back': ['left', 'c', 'backspace'],
#             'keymap.forward': ['right', 'v'],
#             'keymap.fullscreen': ['f', 'ctrl+f'],
#             'keymap.grid': ['g'],
#             'keymap.home': ['h', 'r', 'home'],
#             'keymap.pan': ['p'],
#             'keymap.quit': ['ctrl+w', 'cmd+w'],
#             'keymap.save': ['s', 'ctrl+s'],
#             'keymap.xscale': ['k', 'L'],
#             'keymap.yscale': ['l'],
#             'keymap.zoom': ['o'],
#             'legend.borderaxespad': 0.5,
#             'legend.borderpad': 0.4,
#             'legend.columnspacing': 2.0,
#             'legend.fancybox': False,
#             'legend.fontsize': 'large',
#             'legend.frameon': True,
#             'legend.handleheight': 0.7,
#             'legend.handlelength': 2.0,
#             'legend.handletextpad': 0.8,
#             'legend.labelspacing': 0.5,
#             'legend.loc': 'upper right',
#             'legend.markerscale': 1.0,
#             'legend.numpoints': 2,
#             'legend.scatterpoints': 3,
#             'legend.shadow': False,
#             'lines.antialiased': True,
#             'lines.color': 'b',
#             'lines.dash_capstyle': 'butt',
#             'lines.dash_joinstyle': 'round',
#             'lines.linestyle': '-',
#             'lines.linewidth': 1.5,
#             'lines.marker': 'None',
#             'lines.markeredgewidth': 0.5,
#             'lines.markersize': 6.0,
#             'lines.solid_capstyle': 'projecting',
#             'lines.solid_joinstyle': 'round',
#             'mathtext.bf': 'serif:bold',
#             'mathtext.cal': 'cursive',
#             'mathtext.default': 'regular',
#             'mathtext.fallback_to_cm': True,
#             'mathtext.fontset': 'cm',
#             'mathtext.it': 'serif:italic',
#             'mathtext.rm': 'serif',
#             'mathtext.sf': 'sans\\-serif',
#             'mathtext.tt': 'monospace',
#             'patch.antialiased': True,
#             'patch.edgecolor': 'k',
#             'patch.facecolor': 'b',
#             'patch.linewidth': 1.0,
#             'path.effects': [],
#             'path.simplify': True,
#             'path.simplify_threshold': 0.1111111111111111,
#             'path.sketch': None,
#             'path.snap': True,
#             'pdf.compression': 6,
#             'pdf.fonttype': 3,
#             'pdf.inheritcolor': False,
#             'pdf.use14corefonts': False,
#             'pgf.debug': False,
#             'pgf.preamble': [''],
#             'pgf.rcfonts': True,
#             'pgf.texsystem': 'xelatex',
#             'plugins.directory': '.matplotlib_plugins',
#             'polaraxes.grid': True,
#             'ps.distiller.res': 6000,
#             'ps.fonttype': 3,
#             'ps.papersize': 'letter',
#             'ps.useafm': False,
#             'ps.usedistiller': False,
#             'savefig.bbox': None,
#             'savefig.directory': '~',
#             'savefig.dpi': 100.0,
#             'savefig.edgecolor': 'w',
#             'savefig.facecolor': 'w',
#             'savefig.format': 'png',
#             'savefig.frameon': True,
#             'savefig.jpeg_quality': 95,
#             'savefig.orientation': 'portrait',
#             'savefig.pad_inches': 0.1,
#             'savefig.transparent': False,
#             'svg.fonttype': 'path',
#             'svg.image_inline': True,
#             'text.antialiased': True,
#             'text.color': 'k',
#             'text.dvipnghack': None,
#             'text.hinting': True,
#             'text.hinting_factor': 8,
#             'text.latex.preamble': [''],
#             'text.latex.preview': False,
#             'text.latex.unicode': False,
#             'text.usetex': False,
#             'timezone': 'UTC',
#             'toolbar': 'toolbar2',
#             'verbose.fileo': 'sys.stdout',
#             'verbose.level': 'silent',
#             'webagg.open_in_browser': True,
#             'webagg.port': 8988,
#             'webagg.port_retries': 50,
#             'xtick.color': '.15',
#             'xtick.direction': 'in',
#             'xtick.labelsize': 'medium',
#             'xtick.major.pad': 4.0,
#             'xtick.major.size': 4.0,
#             'xtick.major.width': 0,
#             'xtick.minor.pad': 4.0,
#             'xtick.minor.size': 2.0,
#             'xtick.minor.width': 0,
#             'ytick.color': '.15',
#             'ytick.direction': 'in',
#             'ytick.labelsize': 'medium',
#             'ytick.major.pad': 4.0,
#             'ytick.major.size': 4.0,
#             'ytick.major.width': 0,
#             'ytick.minor.pad': 4.0,
#             'ytick.minor.size': 2.0,
#             'ytick.minor.width': 0,
#           }
# mpl.rcParams.update(rcParams)


