name: Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 src
    - name: Plot tests
      run: |
        python -m pytest tests -s