# As of v0.5.4, python 3.6 testing is deprecated
name: Tests

on:
  - push

jobs:
  test:
    runs-on: macos-12

    strategy:
      matrix:
        python-version: ['3.8', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        # echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        # sudo apt install msttcorefonts -qq
        # rm ~/.cache/matplotlib -rf
    - name: Lint with flake8
      run: |
        flake8 src
    - name: Plot tests
      run: |
        python -m pytest tests -s
